# Generated by Django 5.2.4 on 2025-07-20 15:46

import skilltracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltracker', '0003_alter_tasks_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=skilltracker.models.DataMixin.get_status_choices, default='new'),
        ),
    ]
