# Generated by Django 5.2.4 on 2025-07-22 18:24

import skilltracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltracker', '0004_alter_comments_options_alter_tasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=skilltracker.models.DataMixin.get_status_choices, default='new', max_length=50),
        ),
    ]
