# Generated by Django 5.2.4 on 2025-07-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_profile',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='image_for_users/'),
        ),
    ]
